### PR TITLE
Change install url to using git.io/omf

### PR DESCRIPTION
**Pull request by bucaran**
From 

```fish
curl -L https://github.com/bpinto/oh-my-fish/raw/master/tools/install.fish | fish
```

to

```fish
curl -L git.io/omf | fish
```

:smiley:

### CODE REVIEW

**Comment by bucaran** [comment]
LOL Stupid travis

**Comment by bpinto** [comment]
What is the advantage? It seems to hide information and will make it harder to do changes.

**Comment by bucaran** [comment]
It is clearly more readable, easier to copy paste and it is just an alias to the main URL. I used tiny to generate it. Remember git.io?

**Comment by bucaran** [comment]
BTW I think the error could be related to changes in the latest fish build. We need to call the debug squad.

**Comment by bucaran** [comment]
We are back to normal.

@bpinto Vanity URLs are the norm man :)

[GitHub Vanity URLs](https://github.com/blog/985-git-io-github-url-shortener)

**Comment by bpinto** [comment]
If the URL changes, how do we update the shortened link?

I can't see any advantage of using this link.

**Comment by bucaran** [comment]
The URL should _never_ change.

Advantages:
+ Short and Cool.

**Comment by bpinto** [comment]
Problem is, you know it is going to change. :)

**Comment by bucaran** [comment]
Is it going to? What do you mean?

**Comment by bucaran** [comment]
Will reopen when we become an organization.

**Pull request closed without merging**
