### PR TITLE
Dangerous theme

### PR DESCRIPTION
**Pull request by tannhuber**
I found some spare time to translate my dangerous theme from zsh to fish. It would be the first oh-my-fish theme starting with 'd'. :-)

The functionality is similar to budspencer.
![screenshot][screenshot]
[screenshot]: https://raw.githubusercontent.com/tannhuber/media/master/dangerous.gif

### CODE REVIEW

**Comment by bucaran** [comment]
Hey @tannhuber! I love budspencer, but how's this theme different from it? I know it's not affecting other parts of the code, but there's technical debt associated with any addition.

**Comment by bobthecow** [comment]
@tannhuber What are you using for the colorized `ls` output?

**Comment by tannhuber** [comment]
@bucaran Yes, there're only few changes related to budspencer: 
* It looks differently.
* No powerline font is needed.
* It's possible to hide **all** the segments, not only the PWD segment. (Perhaps I'll change that behaviour in budspencer theme as well. At the moment I'm playing with both alternatives.)

I originally wrote three identical behaving but differently looking themes for zsh, one as default theme, the second one for root shells and the last one for ssh connections. For me it's important seeing at a glance where I am. Besides, I like some variety. The dangerous theme was for root shells. That's the reason why I called it dangerous.

@bobthecow Look here: #435

**Comment by bpinto** [comment]
@tannhuber would you push it here instead? https://github.com/oh-my-fish/theme-dangerous

**Pull request closed without merging**
