### PR TITLE
Improve array.delete

### PR DESCRIPTION
**Pull request by bucaran**
+ Rename `array.delete` to `list.erase` to better suit Fish terminology.
+ Extend to support any number of items and/or lists.
+ Add --from option.

### CODE REVIEW

**Comment by bucaran** [comment]
You can fully test it here.

```fish
function list.erase.test
  function list.erase.test.default
    set -l nums 1 2 3 4 5 6 7 8 9 10 11 12
    set -l odds 1 3 5 7 9 11

    list.erase 12 nums
    contains -- 12 $nums
      and return 1

    list.erase 8 10 nums
    contains -- 8 $nums
      and return 1
    contains -- 10 $nums
      and return 1

    list.erase 2 --from nums
    contains -- 2 $nums
      and return 1

    list.erase 4 6 --from nums
    contains -- 4 $nums
      and return 1
    contains -- 6 $nums
      and return 1

    list.erase 1 --from nums odds
    contains -- 1 $nums
      and return 1
    contains -- 1 $odds
      and return 1

    list.erase 3 5 7 9 11 --from nums odds
    test -n "$nums"
      and return 1
    test -n "$odds"
      and return 1
    return 0 # Success
  end
  list.erase.test.default
    and echo ✔
    or echo ✘
end
```

**Comment by bpinto** [comment]
I have merged this and added tests using `fish-spec`.

**Comment by bucaran** [comment]
I am almost done wrapping the test to work with travis, would you mind reversing this merge and wait for my final PR?

**Comment by bpinto** [comment]
You can open a new PR and I'll rebase instead of reversing this commit, I think it will make the git log look better.

It should count for you:
screen shot 2015-01-10 at 15 57 53

I just commited, you authored.

**Comment by bucaran** [comment]
OK. I will open a new PR with everything from `list.erase`. I still need some time.

**Pull request closed without merging**
