### PR TITLE
Awesome README + @marcker's Logo

### LINKED ISSUE #380: Oh-my-fish logo
Wants website...

Just thinking out loud.

### PR DESCRIPTION
**Pull request by bucaran**
Thanks @marcker for the awesome logo.

Closes #380

### CODE REVIEW

**Comment by marcker** [comment]
I was happy to contribute.

**Comment by bucaran** [comment]
Thanks again.

I added a better attribution you can check in the README.

:+1:

**Comment by bpinto** [comment]
@bucaran What is the relation between oh-my-fish and recipes?

I don't see a reason to have it as a link.

**Comment by bucaran** [comment]
Thanks for noticing, will remove asap.

**Pull request merged**
