### PR TITLE
Add a screenshot for the theme.

### PR DESCRIPTION
**Pull request by mtahmed**
The link I had before went down so I updated the link for the screenshot.

### CODE REVIEW

**Comment by bpinto** [comment]
Could you instead upload the picture as a comment and link it on the README? Github won't remove it. :)

**Comment by xorgy** [comment]
mtahmed

**Comment by xorgy** [comment]
I did this for him, and put it in pull request #354.

**Comment by bpinto** [comment]
:+1: thanks both of you!

**Pull request closed without merging**
