### PR TITLE
Added extends plugin

### PR DESCRIPTION
**Pull request by titosemi**

### CODE REVIEW

**Comment by titosemi** [comment]
@bpinto Happy new year! 
Too much work or travelling again? :smile:

**Comment by bpinto** [comment]
I was waiting for you to ping me. I don't open the pull requests unless github notifies me.

**Comment by bpinto** [comment]
@titosemi have you had time to go through the readme?

**Comment by bucaran** [comment]
@titosemi Have you been using the extends function lately?

**Comment by titosemi** [comment]
Hey!

Yes, I use it in my daily basis :)

I'm currently on holidays and without computer :( 
Will be back around the 23rd of February.

**Comment by bucaran** [comment]
@titosemi Let's talk about it later then. Enjoy your holidays! :smile:

**Comment by bucaran** [comment]
@titosemi I will be temporarily closing this PR until @titosemi is back. Feel free to reopen when you are ready to continue:)

**Comment by titosemi** [comment]
Hi @bucaran!

Sadly my holidays are over, so i'm back.

Apart from the Readme, is there anything else pending?

**Comment by bucaran** [comment]
@titosemi That's too bad!

OK. So, first let's tidy up that README.

After, have you looked at [fish-spec](https://github.com/bpinto/oh-my-fish/tree/master/plugins/fish-spec)? What do you think about writing some tests for extends?

:smiley:

**Comment by titosemi** [comment]
Oh! [fish-spec](https://github.com/bpinto/oh-my-fish/tree/master/plugins/fish-spec) **Nice!!!!!!**

Will try to find some time to play with it!

**Comment by bucaran** [comment]
:+1: Some plugins are already using _fish-spec_, so you can use that to get started quickly. `tiny` for instance, grabs a github URL and outputs its minified version. See [here](https://github.com/bpinto/oh-my-fish/tree/master/plugins/tiny/spec) how the tests were implemented.

**Pull request closed without merging**
