### PR TITLE
Fix for bobthefish ruby version segment

### LINKED ISSUE #370: bobthefish theme question
Great work on oh-my-fish - coming from ZSH I appreciate it, but even more so the differences!

I have been trying to get `bobthefish` theme to work as shown on http://bleibinha.us/blog/2014/08/my-command-line-setup-with-fish#bobthefish but I am stuck with a red chevron at the start of every single prompt.
Screenshot
 No matter where I am in the file system, it's present. If I switch to the `agnoster` theme this isn't present.

Is there an issue with my configuration? Thanks

### PR DESCRIPTION
**Pull request by bobthecow**
… when there's no version to show.

Fixes #370

### CODE REVIEW

**Comment by bpinto** [comment]
Waiting for @pbowyer confirmation.

**Comment by bobthecow** [comment]
He's not going to confirm until tomorrow :)

**Comment by bpinto** [comment]
No longer waiting then :)

**Comment by bobthecow** [comment]
:)

**Comment by pbowyer** [comment]
Works great guys, thanks :)

**Comment by bobthecow** [comment]
Awesome!

**Pull request merged**
