### PR TITLE
adding a dockerfile

### PR DESCRIPTION
**Pull request by bpinto**
```
docker build -t oh-my-fish .
docker run -t oh-my-fish
```

### CODE REVIEW

**Comment by bpinto** [comment]
@bucaran with the dockerfile, I can now run the tests on linux and reproduce the failing tests.

**Comment by bucaran** [comment]
Great addition. No more chronic travis fear!

**Comment by bucaran** [comment]
BTW how can I run `getopts` tests only without modifying the `CMD` in the Dockerfile?

**Comment by bobthecow** [comment]
`docker run foo` overrides `CMD`.

**Comment by bpinto** [comment]
`docker run -i -t oh-my-fish fish "/src/plugins/getopts/getopts.spec.fish"`

**Comment by bucaran** [comment]
Thanks @bobthecow @bpinto

**Comment by bucaran** [comment]
Wish I didn't have to rebuild the container every time I change the code though...

**Comment by bobthecow** [comment]
it should only be rebuilding from line 17 on, right?

**Comment by bucaran** [comment]
Yes, that's right. 

But changes I make to `getopts.fish` are not read when I `docker run -t oh-my-fish`.

**Comment by bpinto** [comment]
You don't need to rebuild.

`docker run -i -t oh-my-fish -v ~/.oh-my-fish:/src fish "/src/plugins/getopts/getopts.spec.fish"`

**Comment by bucaran** [comment]
Changes I make to getopts.fish are not read when docker run -t oh-my-fish. It is using the same original image it created when I first run docker build..., changes I make to the spec/test file do seem to go through though.

**Comment by bpinto** [comment]
No changes should go through, unless you add that -v argument.

**Comment by bucaran** [comment]
Any thoughts

`exec: "-v": executable file not found in $PATH
FATA[0000] Error response from daemon: Cannot start container b022e83cfa5583ef3bde6cbf578274406dfa222e76bd0221a628c73f84423800: exec: "-v": executable file not found in $PATH`

**Comment by bpinto** [comment]
Sorry, `-v` needs to come before `-t`

`docker run -i  -v ~/.oh-my-fish:/src -t oh-my-fish fish "/src/plugins/getopts/getopts.spec.fish"`

**Comment by bucaran** [comment]
It correctly reads my updated spec, but it does not read any changes to `getopts`.

**Comment by bpinto** [comment]
```
docker run -i -t oh-my-fish cat "/src/plugins/getopts/getopts.fish"
docker run -i -t oh-my-fish cat "/src/plugins/getopts/getopts.spec.fish"
```

Should show the files when you ran `docker build`. These files should not be modified unless you run `docker build` or `docker run` with `-v`.

**Comment by bucaran** [comment]
What would be the workflow to debug / test and run?

I make some changes to either `getopts.fish` or `getopts.spec.fish`, then:

+ docker build -t oh-my-fish .
+ docker run -t oh-my-fish fish "/src/plugins/getopts/getopts.spec.fish"

I thought that would be it, but it does not read changes from `getopts.fish`, only from the spec.

**Comment by bpinto** [comment]
That should update `getopts.fish` too. All files inside `~/.oh-my-fish` should be updated.

Run the cat function above to confirm that the file changed after running `docker build`.

**Comment by bucaran** [comment]
The cat function does show me the updated source of `getopts.fish`, but `docker run -t..` still runs the older version.

BTW, there seems to be a bug in fish `seq` when used in reverse. Anyone on linux try `seq 5 1` it does not work.

**Comment by bpinto** [comment]
`seq 5 1` does not work for me either on ubuntu running on docker.

**Comment by bucaran** [comment]
fish-shell/fish-shell/issues/1914

**Comment by bpinto** [comment]
@bucaran these are the correct instructions now, note that in order to run with local code, you need to use `-v` option now.

Okay, the dockerfile is in a more common way now.

To build the image using ONLY data from github:
```
docker build -t oh-my-fish
```

To run the tests using ONLY data from github:
```
docker run -t oh-my-fish #Runs all tests
docker run -t oh-my-fish fish "/root/.oh-my-fish/plugins/getopts/getopts.spec.fish"
```

To run the tests using LOCAL data:
```
docker run -v (pwd):/root/.oh-my-fish -t oh-my-fish #Runs all tests
docker run -v (pwd):/root/.oh-my-fish -t oh-my-fish fish "/root/.oh-my-fish/plugins/getopts/getopts.spec.fish"
```

**Comment by bucaran** [comment]
One problem is that on OS X, I don't need to specify the step increment in `seq 5 1`, but it was required on Ubuntu running on Docker. I added that and now all my tests pass locally.

The bad news is I pushed and travis is still failing.

**Comment by bpinto** [comment]
Adding -1 worked on my docker machine.

**Comment by bucaran** [comment]
I will create a new PR with the changes.

**Pull request merged**
