### PR TITLE
Modifying bak plugin tests to use fish spec

### PR DESCRIPTION
**Pull request by bpinto**
Also improved `--to-contain` to check multiple individual arguments.

### CODE REVIEW

**Comment by bpinto** [comment]
One test is breaking, but I can't reproduce locally.

Need to improve error handling of `fish-spec`.

**Comment by bucaran** [comment]
Which one?

**Comment by bpinto** [comment]
It was failing before, I think I fixed in a previous commit to `expect`. Want to review this PR?

**Comment by bucaran** [comment]
Let's fix `expect`. I am trying to reproduce the test that you mentioned was failing:

```fish
expect 'a' --to-equal 'b'
```

**Comment by bpinto** [comment]
What do you mean, fix `expect`?

**Comment by bucaran** [comment]
Nevermind!

**Pull request merged**
