### PR TITLE
themes: add a new theme, scorphish

### PR DESCRIPTION
**Pull request by scorphus**
Based on Zish and Coffeandcode themes. Many thanks to their authors!

### CODE REVIEW

**Comment by bucaran** [comment]
Thanks. Can you fix the image?

**Comment by scorphus** [comment]
The link to the image points to bpinto/oh-my-fish/master/themes/scorphish/scorphish_preview.png, which until now does not exist. But once this pull request is merged, the image will exist in such location.

However, I can change the link to point to my fork.

**Comment by bucaran** [comment]
@scorphus Exactly. Please remove the image from the repo, insert the image in a comment, for example here, copy the GitHub URL and link to it instead. Finally you can `push origin scorphish --force` :smile: 

Check out [CONTRIBUTING](https://github.com/bpinto/oh-my-fish/blob/master/CONTRIBUTING.md#themes).

**Comment by scorphus** [comment]
Oh, sorry for not reading docs on contributing in the first place.

Please ignore my next forced push, I'll use it just to generate a more detailed image. Then I'll make a third valid forced push.

**Comment by scorphus** [comment]
screen shot 2015-05-02 at 11 35 31 pm

**Comment by scorphus** [comment]
There you go!

Thanks for that nitty comment-with-an-image tip :+1:

**Comment by bucaran** [comment]
Thanks! I will probably give it a try. It looks very nice.

**Comment by scorphus** [comment]
@bucaran Awesome! I'm so glad you like it! Did you give it a try? What do you think? Any suggestion? I'm all ears :smiley:

**Comment by bucaran** [comment]
@scorphus I love it. I am using it now. What is the `zero` supposed to mean btw?

**Comment by scorphus** [comment]
@bucaran That's so cool!

And I really like the idea of having the number of ahead commits. Nice that you've implemented it. Once we're done with these improvements we update the screenshot.

**Pull request merged**
