### PR TITLE
Add git functions

### PR DESCRIPTION
**Pull request by ubermonkey**
Bunch of git shortcuts for fish shell

### CODE REVIEW

**Comment by bucaran** [comment]
@ubermonkey Thanks! But I think git shortcuts are better left off to the user. I personally prefer using a `.gitconfig`. [For example](https://gist.github.com/pksunkara/988716).

**Comment by ubermonkey** [comment]
@bucaran ok. I just thought that user should be able to enable `git` plugin in the `config.fish`. 'Cause I prefer to control everything about shell commands from shell config, and personally I missed git plugin.

**Comment by bobthecow** [comment]
You absolutely can put it in your shell, but as @bucaran says, shortcuts are a personal thing, so we've avoided adding them to the global project. oh-my-fish supports personal plugins: just drop this `git` folder in `.config/oh-my-fish/plugins/` and it'll work the same as if it were in the global oh-my-fish folder.

**Comment by bucaran** [comment]
@ubermonkey What @bobthecow said! :smile:

**Comment by ubermonkey** [comment]
I've took a look on other plugins, that what you say make sense, now I agree that 'bunch of shortcuts' is not enough to be a plugin. Sorry for disturbing.

**Comment by bucaran** [comment]
@ubermonkey It's cool dude. Worry not.

**Pull request closed without merging**
