### PR TITLE
Add msg plugin

### PR DESCRIPTION
**Pull request by bucaran**
```
   __ _  ___ ___ _
  /  ' \(_-</ _ `/
 /_/_/_/___/\_, /
           /___/ v0.1.0

NAME
     msg - technicolor message printer

SYNOPSIS
     msg [-sn] @<fg:bg> [style]<text>[style]

OPTIONS
     -s
         Do not separate arguments with spaces.
     -n
         Do not output a newline at the end of the message.

STYLES
     _text_                 Bold
     __text__               Underline
     ___text___             Bold and Underline
     /directory/            Directories
     [url]                  Links
     \n                     Line Break
     \t                     Tab Space

     @<fg:bg> fg=bg=RGB|RRGGBB|name|random
       RGB value can be any three to six hex digit or color name.
       e.g, @0fb, @tomato, @random, @error, @ok.

AUTHORS
     @bucaran (Jorge Bucaran)

v. 0.1.0
```

See #283 for more info.

### CODE REVIEW

**Comment by bucaran** [comment]
msg 

## Internals

### Local Functions
> __Note__: The following convention is used for naming local functions `module_name_._.command`.

### `function --no-scope-shadowing msg._.set.color`
Set style, fg/bg colors and reset the color again. This function modifies variables in the parent scope.
`params [<fg>] [<bg>] [<style>]`

### `function msg._.str.has`
True if substring exists in string. Used to cascade apply `-sn` options when `msg` is called.
`params <substring> <string>`

### `function msg._.str.grab`
Extract string between left and right separators of variable length. Used to grab the part inside the style separators. `_bold_, __underline__, ___bold_and_underline___, [urls], /directories/`
`params <left-sep> [<right-sep>] <string>`

### `function msg._.random.color`
Print a random `RRGGBB` hexadecimal color. 

### `function msg._.get.color`
Translate color names to valid RRGGBB hexadecimal value. This function takes the bulk of the code in the module as it checks for all 256 color names.
`params <color|random>`

**Comment by bpinto** [comment]
I need to have my computer with me to review this properly, tomorrow possibly

**Comment by bucaran** [comment]
I will submit a new cleaner PR with `require_plugin` and `msg`.

**Comment by bucaran** [comment]
[I have submited a new and cleaner PR with `require_plugin` and `msg`.](https://github.com/bpinto/oh-my-fish/pull/287)  __Do not merge this PR.__

**Pull request closed without merging**
