### PR TITLE
"new" theme: bira-fishface

### PR DESCRIPTION
**Pull request by duarte-pompeu**
Merged some of the things I liked in the bira and fishface themes to make this one.

Feel free to include it in your repo if you like it.

### CODE REVIEW

**Comment by bpinto** [comment]
Could you read the [contribution guide](https://github.com/bpinto/oh-my-fish/blob/master/CONTRIBUTING.md) and make the proper updates?

**Comment by duarte-pompeu** [comment]
Oh, I'm sorry, didn't see it. I'll get into it!

**Comment by duarte-pompeu** [comment]
It's passing all the tests and I cleaned up the code to follow the style guide.

However, I'm new to this and I have no idea how to delete the screenshot file from the pull request.

**Comment by amio** [comment]
The simplest way is to create a new branch, do your modification, and then submit a new pull request.

**Comment by bpinto** [comment]
You need to remove the screenshot from git and commit it. Later you just need to squash all commits into one.

```
git add upstream git@github.com:bpinto/oh-my-fish.git
git rm themes/bira-fishface/bira-fishface.png
git add -A themes/bira-fishface/bira-fishface.png
git commit -m 'removing screenshot'
git rebase -i upstream/master
```

When the rebase window displays, mark all commits but the first to be squashed.

**Comment by bpinto** [comment]
ping @duarte-pompeu

**Comment by duarte-pompeu** [comment]
I think I'm gonna just do @amio said, I'm a git newbie and this is getting a bit too complex for me.

**Pull request closed without merging**
