### PR TITLE
Autoloading on plugin add.

### PR DESCRIPTION
**Pull request by bucaran**
> This is a minor commit, but it helps creating more consistent plugin `load` files, it also adds a simple solution for plugin interdependency #88.

This is our current plugin loading strategy:

```fish
# Add all defined plugins
for plugin in $fish_plugins
  _fish_add_plugin $plugin
  _fish_add_completion $plugin
  _fish_source_plugin_load_file $plugin
end
```

If your plugin requires another plugin to work, you should be able to do so inside your `myplugin.load` like:

```fish
_fish_add_plugin plugin
```

This works for simple plugins with only a `plugin.fish` function file, but will fail to source the plugin's load file which is how additional dependencies are defined / required in a per-plugin basis.

`_fish_add_plugin` should automatically source load files and completions.

### CODE REVIEW

**Comment by bucaran** [comment]
If anybody knows why two of my past contributions are showing up on this PR, please let me know the reason.

**Comment by bpinto** [comment]
You need to rename your branch with master. Your master branch could also be outdated compared to the upstream one.

**Comment by bpinto** [comment]
I like the simplification, I'm not sure yet if we shouldn't have another function (could be an alias) called require_plugin or something similar. What's your opinion?

My thinking is that it would have a more descriptive name , _functions were created with the goal of being private functions.

**Comment by bucaran** [comment]
I know for sure my branch is up to date with upstream, but let me check again.

That is also an option. This simple change does not create anything new since fish_add_plugin is a core function.

So, do you prefer creating a new function require_tree to add plugins along with completetions and .load sourcing? 

_prepend_tree should be renamed as well since it is not intended to be private.

**Comment by bpinto** [comment]
:+1: 

The doors are always open. :)

**Pull request closed without merging**
