### PR TITLE
seq call in getopts should specify negative step

### PR DESCRIPTION
**Pull request by bucaran**
This fixes bugs in Ubuntu running on docker. OS X tests still pass. Travis build is falling.

### CODE REVIEW

**Comment by bpinto** [comment]
Let's see if we still need to fix travis build... =/

**Comment by bpinto** [comment]
We need to fix the travis workflow... =/

**Comment by bucaran** [comment]
Are we running the same Linux travis is running?

**Comment by bpinto** [comment]
Travis didn't fetch your changes, that is why they were failing. On master it is green now.

**Comment by bucaran** [comment]
Oh, _travis_.

**Comment by bpinto** [comment]
@bucaran can you add `git status` to `script/run-tests.fish` and push it to your fork? Possibly opening a pull request here? I want to confirm if the git commit is now correctly fetched.

```
#!/usr/bin/env fish

git status
set -l result 0
for test in (find $fish_path -type f -print | grep "spec.fish")
  fish $test $argv
    or set result 1
end
exit $result
```

**Comment by bucaran** [comment]
@bpinto I am back. Do you still want me to do this or were you able to confirm travis is fetching what it needs to fetch?

**Comment by bpinto** [comment]
I can't confirm as Travis for me has the same repo but different branch, I would like you to test it as it would be not only from a different branch but also from a different repo.

**Pull request merged**
