### PR TITLE
Fish spec up

### PR DESCRIPTION
**Pull request by bucaran**
Update from last review session. Let's merge this one and work it from here.

### CODE REVIEW

**Comment by bucaran** [comment]
Obviously it fails because it's using a different `fish-spec`.

**Comment by bpinto** [comment]
Could you rebase this?

**Comment by bucaran** [comment]
What are TRAVIS_BRANCH and TRAVIS_REPO_SLUG?

**Comment by bpinto** [comment]
http://docs.travis-ci.com/user/ci-environment/#Environment-variables

**Comment by bucaran** [comment]
I am getting this
```
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git reset'
rebase in progress; onto 5c7f594
You are currently rebasing branch 'fish-spec-up' on '5c7f594'.

nothing to commit, working directory clean
```
Mmm

**Comment by bpinto** [comment]
I have no idea what you are running into. :P

**Comment by bucaran** [comment]
Thanks for the link!

**Comment by bucaran** [comment]
I know how to fix that gitssue!

**Comment by bucaran** [comment]
> http://docs.travis-ci.com/user/ci-environment/#Environment-variables
Thanks for the link!

Let me fix that...

OK!

**Comment by bpinto** [comment]
Why are the tests failing?

**Comment by bucaran** [comment]
Can you send me a screenshot?

**Comment by bpinto** [comment]
image

**Comment by bucaran** [comment]
This is FUN! :smile:

**Comment by bucaran** [comment]
Can you try running specific tests to see if anything is passing?

**Comment by bpinto** [comment]
They all have the same error. :P
Maybe your rebase? Because before you rebased, it was working fine.

**Comment by bpinto** [comment]
```
function spec.eval
  set -l result 1#$status
```

**Comment by bucaran** [comment]
Just fixed that and pushed to my master.
Travis: https://travis-ci.org/bucaran/oh-my-fish/builds/47324578

**Comment by bpinto** [comment]
If you push it to this branch, the tests should go green too.

**Comment by bucaran** [comment]
Sorry for opening a new PR, but now that the tests are passing over there, will close this and continue the discussion over there. We have a green build.

**Pull request closed without merging**
