### PR TITLE
Agnoster ruby_prompt

### PR DESCRIPTION
**Pull request by rocknrollMarc**
I added a ruby prompt on the right side, I need to fr work :)

### CODE REVIEW

**Comment by rocknrollMarc** [comment]
Ah ok get you. Are you sure that a good idea? I have just recently discovered zsh and fish shell and for people who are not that into shell scripting its kind of difficult and they might not know that you can do that. Otherwise Ill do it.

**Comment by bpinto** [comment]
That's why it's important to have a README file, so when they are viewing the theme, they can also read about its functionality.

**Comment by rocknrollMarc** [comment]
Ah ok. Sure ok then Ill do that in the next days as I really like agnoster with the ruby thing. Actualy I think on presto they have added it to agnoster funny

**Comment by bucaran** [comment]
@rocknrollMarc Hi. How is it going?

**Comment by rocknrollMarc** [comment]
LoL yes time flys by doesnt it ill try doing that today got some free time

**Comment by bucaran** [comment]
:+1: Closing until @rocknrollMarc is back.

**Pull request closed without merging**
