### PR TITLE
Add 'will' theme

### PR DESCRIPTION
**Pull request by williamhogman**
Hello there,

I don't know if you still accept theme submission but here goes.

Screenshot

A very simple theme, based on three things:
- Simple prompt with ⊨ (logical entailment, aka double turnstile)
- Working directory on the right
- Hostname only on SSH.

All the best,
/will

### CODE REVIEW

**Comment by bucaran** [comment]
Of course we do. Would you mind adding the image link to the README? 

First, upload the image to your post and link from GitHub directly instead of a 3rd party like DropBox. We don't know how long that image will be there, what if you decide to change the URL or remove the picture?

Cheers.

**Comment by williamhogman** [comment]
Okay, I uploaded it to github and added that link to the PR and readme

Cheers!

**Comment by bucaran** [comment]
:+1: Why are you using the double turnstile? Nice.

**Comment by williamhogman** [comment]
Awesome! :)

> :+1: Why are you using the double turnstile? Nice.
Previously I used a right arrow, but when I ported my stuff to from zsh to fish, I figured I'd try something else. I like the way it focuses my eyes on the begining off the line.

**Pull request merged**
