### PR TITLE
Updated l theme to have rbenv support

### PR DESCRIPTION
**Pull request by rahult**
This branch should be rebased against upstream/master

### CODE REVIEW

**Comment by rahult** [comment]
Duplicate of https://github.com/bpinto/oh-my-fish/pull/362. Was not sure how to rebase again master with my individual commits on the fork master branch so I have create a new pull request using a new branch.

**Comment by bucaran** [comment]
Usually, `git pull --rebase upstream master` will do just that. It will pull new changes from upstream, apply them to your working copy of the repo and re apply your commits on top of that, then it's as if we were all in sync :D

**Comment by rahult** [comment]
Awesome thanks, I will keep this tip handy, rebasing not my strong suite :smile:

**Comment by bucaran** [comment]
@rahult 

Create a new test repo here in Github with a README.
Clone it. `git clone https://github.com/rahult/testrepo`
Create some sample files locally. `touch A B C D E`
Add them to git and commit. `git add -A; git commit -m "Add A B C D and E"
__Now__, from the GitHub web interface, edit the README file, commit some dummy text. You notice now both remote (GitHub) and local repos are _out of sync_, GitHub has some changes you don't have locally.
Before you can push your new local commits to the remote, you need to pull remote changes. There ways to do this, but in this case the easiest and most straight forward way would be `git pull --rebase origin master`, this updates your local copy with the README changes and adds the sample files commit on top of that.
Finally, `git push origin master`.

**Comment by rahult** [comment]
Thanks @bucaran,

Just went through the same thing on StackOverflow

Have changed my workflow to use rebase instead of merge

```fish
alias gfp='git pull --rebase upstream master'
```

Previously the merge strategy was causing all that branching :smile: happy with this setup now. 

Thanks for your suggestion.

**Pull request merged**
