### PR TITLE
use existent plugins as examples in the README.md

### LINKED ISSUE #397: git plugin
Just wondering, the README.md mentions a git plugin, but the `plugins` folder does not contain one. What am I missing here? Is it defined elsewhere?

### PR DESCRIPTION
**Pull request by despairblue**

### CODE REVIEW

**Comment by bucaran** [comment]
Thank you @despairblue . Do you mind rebasing?

**Comment by despairblue** [comment]
nope, just a moment...

**Comment by despairblue** [comment]
done

**Comment by despairblue** [comment]
@bucaran I assume you mean the PR title, not the commit message, right?

**Comment by despairblue** [comment]
ah, reading the issues comment, I now assume you mean the commit message.

**Comment by bucaran** [comment]
Yup. Thanks.

**Comment by despairblue** [comment]
Like this?

**Comment by bucaran** [comment]
:+1:

**Pull request merged**
