### PR TITLE
ta-to-done :ledger:

### PR DESCRIPTION
**Pull request by bucaran**
Very nice little utility I am currently using to try to increase my productivity.

I would love to see this included in Oh-my-fish.

Please see [README](https://github.com/bucaran/ta/blob/master/README.md) to learn more.

Main repository has two extra files under `tools/install` and `tools/uninstall` that are not included in this PR, since this is the plugin version.

I am currently working on a spec, but would like to start code reviewing this whenever possible.

> __Note__: What should I do about the images?

### CODE REVIEW

**Comment by bpinto** [comment]
I will check this tomorrow.

I'm moving house, so free time is scarce. :P

**Comment by bucaran** [comment]
Nice! No worries, take your time :smile: 

Thank you!

**Comment by bucaran** [comment]
I have been using this for a while without apparent problems, so I will go ahead and merge. Hopefully I will get around adding tests sometime. :feelsgood:

**Comment by bpinto** [comment]
@bucaran you know we can not add images to git... Look at the amount of images that were introduced...

**Comment by bucaran** [comment]
Indeed. Will fix asap :+1:

**Comment by bpinto** [comment]
Don't know how to fix those... we would need to remove the image from git but that should involve changing the history and that just can not happen on a public branch.

**Comment by bpinto** [comment]
I believe we can no longer remove the images from git history, only from git. Which would not decrease the size of the repo.

**Comment by bucaran** [comment]
Indeed. My bad.

**Comment by bpinto** [comment]
No worries, it happens!

**Pull request merged**
