### PR TITLE
Add nai theme.

### PR DESCRIPTION
**Pull request by xorgy**

### CODE REVIEW

**Comment by bucaran** [comment]
Hi. Can you upload the picture as a comment and link it on the README?

**Comment by xorgy** [comment]
Sure.

**Comment by xorgy** [comment]
nai

**Comment by bucaran** [comment]
:+1:

**Comment by bpinto** [comment]
Which font is this? What about color theme? That looks nice.

**Comment by xorgy** [comment]
The font is Envy Code R, and the colour scheme is the default fish colours
with a custom palette in my terminal.
2015/01/29 17:06 "Bruno" <notifications@github.com>:

**Pull request closed without merging**
