### PR TITLE
Added lambda theme which includes rbenv helpers

### PR DESCRIPTION
**Pull request by rahult**
Characteristics

- Working directory
- Git branch and dirty state (if inside a git repo)
- Rbenv Ruby Version
- Rbenv Ruby Gemset

### CODE REVIEW

**Comment by bpinto** [comment]
If this is the same but has the right_prompt, can't we improve the original one? And using a environment variable we enable this right prompt or not?

**Comment by rahult** [comment]
Good idea @bpinto, I will update the 'l' theme

**Comment by bpinto** [comment]
ping @rahult

**Comment by rahult** [comment]
Sorry @bpinto, Got swamped at work. I will make the necessary changes in the next 24 hours.

**Comment by bpinto** [comment]
:+1:

**Comment by rahult** [comment]
Merged the theme into 'l'. To activate the right prompt a variable needs to be set within config.fish.

```fish
set fish_theme_l_right_prompt true
```



:smile: thanks for creating this awesome project

**Comment by bobthecow** [comment]
Is it worth standardizing the main fish theme variables different themes use? `set fish_theme_right_prompt true` could enable the right prompt regardless of which theme you're using. It would be super useful for things like turning on and off RVM/rbenv/virtualenv/etc display, as your needs for those sorts of features wouldn't change depending on your theme.

I might be biased, but I'd suggest [these](https://github.com/bpinto/oh-my-fish/blob/master/themes/bobthefish/fish_prompt.fish#L15-L19) as a starting point:

```
theme_display_git
theme_display_hg
theme_display_virtualenv
theme_display_ruby
theme_display_user
```

**Comment by rahult** [comment]
Wow did not knew that this theme existed. Awesome theme mate :smile: 

I will update the current theme logic to similar to yours over the weekend.

**Comment by bpinto** [comment]
@bobthecow I would like to, I feel more and more the need to have a better way to create themes reusing parts.

**Comment by bobthecow** [comment]
> Wow did not knew that this theme existed. Awesome theme mate :smile:

Thanks!

**Comment by bucaran** [comment]
@bpinto A base theme others could use to derive their one would be a nice thing to have.

**Comment by rahult** [comment]
I agree, base theme would be super useful.

My main use case is to overwrite the right prompt with some useful information like ruby version. Is it possible for extend an existing them in a custom.theme.fish file?

**Comment by bobthecow** [comment]
If that's all you want, you can actually overwrite the right prompt yourself. Just implement the `fish_right_prompt` function.

**Comment by rahult** [comment]
What I meant was "to have a way to use existing theme functionality provided and extend it or re-arrange it"

Almost like, accessing Ruby Version, Python Version, Git Status stuff like which you have already implemented within your theme [bobthefish](https://github.com/bpinto/oh-my-fish/blob/master/themes/bobthefish/fish_prompt.fish#L15-L19) and re-using it and just move some stuff around to customise my right-prompt. 

This way I do not have to duplicate the code to find Ruby version, Python Version or Git Status in any theme I want.

Almost like creating utility methods for themes like Poweline.

Not sure whether this is useful or not

**Comment by bpinto** [comment]
It's not possible yet but something I'm keen on getting back to.

**Comment by bucaran** [comment]
Status on this?

**Comment by bucaran** [comment]
@rahult Hi! What's the status on this?

**Comment by rahult** [comment]
Hi @bucaran I have updated the theme to have rbenv flags using similar pattern as @bobthecow

As existing users might be using this theme already, the rbenv features are disabled by default and have to be explicitly turned on.

If you want any further change please let me know and I will make them straight away.

**Comment by bucaran** [comment]
Awesome. Is this rebased with master?

**Comment by rahult** [comment]
Sorry bucaran, was not sure how to rebase my individual commits as they were in master. So I have created a new pull request https://github.com/bpinto/oh-my-fish/pull/403 which contains a branch which has been rebased again current upstream/master.

Going to bed now, if you need anything else, I can do early morning tomorrow.

**Comment by bucaran** [comment]
Closing this in favor of #403

**Pull request closed without merging**
