### PR TITLE
Improve scorphish theme

### PR DESCRIPTION
**Pull request by scorphus**
Hey, @bucaran, what do you think?

screen shot 2015-05-11 at 10 18 48 pm

Please review and comment!

Thanks!

### CODE REVIEW

**Comment by bucaran** [comment]
LGTM !!

**Comment by scorphus** [comment]
Great! :metal:

Now, IMO, what's left to be done is show proper Git info when a merge, rebase, bisect, cherry-pick, etc. is in progress.

**Comment by bucaran** [comment]
Cool! Thanks.

**Comment by scorphus** [comment]
You're welcome! I'm glad to contribute!

**Comment by bucaran** [comment]
@scorphus :+1:

**Pull request merged**
