### PR TITLE
Improve Edan theme design & function naming.

### PR DESCRIPTION
**Pull request by amio**
And rename function "edan-remote" and "edan-local" to "edan-set-remote"
and "edan-set-local".

### CODE REVIEW

**Comment by bucaran** [comment]
What is visual refined?

**Comment by amio** [comment]
Before:
Screenshot of theme Edan
After:
Screenshot of theme Edan

Summary:

- Exchange order of "user" & "host" ( xiloºXiloMac => XiloMacˇxilo )
- Change git dirty mark icon ( [edan-update] ★  => [edan-update]× )

**Comment by bucaran** [comment]
Nice! That's quite an improvement.

Would you mind rewriting that commit message to something more like:

`Improved edan theme design.`

:+1:

**Comment by amio** [comment]
Of course, since english is not mine native language, my expression may not very accurate express what I thought clearly, really sorry. Thanks for correcting my words, anytime, anywhere ~

I have made a `git push --force`, should be better now :D

**Comment by bucaran** [comment]
No worries :smile:

**Comment by bucaran** [comment]
Looks good to me :+1:

**Pull request merged**
